alias addalias='vim ~/.bash_aliases && source ~/.bash_aliases'
alias mkdir='mkdir -p'
alias hpush='git push heroku master'
alias splitsee='cd ~/projects/splitsee'
alias gpush='git push origin master'
